#!/usr/bin/env python 

import re
import sys

def count_and_print_todos(file_path):
    with open(file_path, "r") as file:
        lines = file.readlines()
        todo_count = 0
        for line in lines:
            if re.search("TODO", line):
                todo_count += 1
                print(line)
        return todo_count

filename = sys.argv[1]
print("Number of TODO items:", count_and_print_todos(filename))

