#!/bin/bash
set -eu
cat <<EOF

------------------------------------------------------------
Usage: 
    $0 [\$1: keywords] [\$2: target path to be searched for]

This guy searches directories for files including keywords.

------------------------------------------------------------
EOF

keyword=$1
target_path=$2
echo "# Files including the keyword '$keyword': "
grep --ignore-case -e $keyword --files-with-matches --recursive $target_path --include=\*.md
