#!/bin/bash
set -eu
#Most frequently used options:
#
#-b  
#    Makes backups of any files in the destination directory that aren’t included in the source. 
#    Commonly used with –backup-dir and –delete switches.
#
#–backup-dir=[path]
#    Allows you to define a name for the backup directory that will be used by the -b option.
#
#–delete 
#    Removes files present in the destination directory that are absent from the source directory.
#
#-z 
#    Compress; uses compression during data transfer. Most often used when using rsync with a remote system.
#
#-n 
#    Dry run; no files are moved. Instead, rsync displays what the results would have been. 
#    Use -n with the -v option to gather additional information.
#
#cf. https://blog.macsales.com/45185-mac-101-learn-the-power-of-rsync-for-backup-remote-archive-systems/
#
#--progress
#   Show progres bar for each file

cat << EOF

Usage:
    $0 [target] [destination]

EOF
origin=$1
to=$2
bk_dir_name="removed_$(date +%Y-%m-%d_%H.%M.%S)"

read -p "Do you have a key? [y/n]:" iskey
read -p "Exclude file [Enter/filename]: " f_excl

if [ $iskey == "n" ]; then
    echo "rsync -azhvb --dry-run --backup-dir=$bk_dir_name --delete ${origin%/} ${to}" --exclude $f_excl > ${to}/dry.log
    echo "" >> ${to}/dry.log
    rsync -azhvb --dry-run --backup-dir=$bk_dir_name --delete ${origin%/} --exclude $f_excl ${to} >> ${to}/dry.log
    vim ${to}/dry.log 
    read -p 'Do you proceed on rsync? [enter]'
    rsync -azhvb --progress --backup-dir=$bk_dir_name --delete ${origin%/} --exclude $f_excl ${to}

elif [ $iskey == "y" ]; then  
    read -p "Type the path to the key:" pathtokey
    echo "rsync -azhvb --dry-run --backup-dir=$bk_dir_name --delete --exclude $f_excl -e "ssh -i $pathtokey" ${origin%/} ${to}" > ${to}/dry.log
    echo "" >> ${to}/dry.log
    rsync -azhvb --dry-run --backup-dir=$bk_dir_name --delete --exclude $f_excl -e "ssh -i $pathtokey" ${origin%/} ${to} >> ${to}/dry.log
    vim ${to}/dry.log 
    read -p 'Do you proceed on rsync? [enter]'
    rsync -azhvb --progress --backup-dir=$bk_dir_name --delete --exclude $f_excl -e "ssh -i $pathtokey" ${origin%/} ${to}
fi
